name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vuln-room:latest

    - name: Save Docker image to tar
      run: docker save vuln-room:latest -o vuln-room.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v4
      with:
        name: vuln-room-image
        path: vuln-room.tar fix this and use ubuntu 24.04